
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.cyrilix.fr
  resources:
  - rules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.cyrilix.fr
  resources:
  - rules/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.cyrilix.fr
  resources:
  - rules/status
  verbs:
  - get
  - patch
  - update
