# permissions for end users to edit rules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rule-editor-role
rules:
- apiGroups:
  - monitoring.cyrilix.fr
  resources:
  - rules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.cyrilix.fr
  resources:
  - rules/status
  verbs:
  - get
